### PR TITLE
Renamed COPYING to LICENCE

### PR DESCRIPTION
**Pull request by s1db**
The licence is the same, I've just renamed the file to keep uniformity.

### CODE REVIEW

**Comment by quozl** [comment]
Why?  Uniformity with what?  In my clones of activities, I've 12 with a LICENSE and 37 with COPYING.

**Comment by s1db** [comment]
Wait. 
Apologies, I was under the assumption that 'LICENCE' is the standard that was being followed since it was flagged as not having a licence here: https://docs.google.com/spreadsheets/d/15XuISn18v4fvq-h_6m53-jc_on9_yi1cQFR71crQkr8/edit#gid=0

I guess it was just an error. Thanks for the heads up though.

**Comment by quozl** [comment]
Thanks, that's interesting.  I don't know who prepared that spreadsheet, when it was prepared, or what tool was used.  It hasn't been discussed on sugar-devel@ as far as I can find, so we don't have consensus.  Presumably it was private.

"Have_License" doesn't say what it means, so it could mean any of;

* has no license metadata in `activity/activity.info`,
* has no license in some source files,
* has no COPYING or LICENSE file.

It would be good to have a standard; and the Wiki is a great place to put it.

**Comment by quozl** [comment]
I'm fine with COPYING, so I'll close this one.

**Pull request closed without merging**
